Update 20171126.md
training-center/plataforma pull request #3
Opened 2017-11-28 11:56 UTC by david81brs

Pontuação e correção de citação.

2017-11-29 13:06 UTC, woliveiras commented on meetings/minutes/doc/20171126.md
> +## Reunião do dia 26/11/2017.
Aqui é um título, mano. 

Pode remover o ponto final?

2017-11-29 13:06 UTC, woliveiras commented on meetings/minutes/doc/20171126.md
> +Precisamos trazer mais pessoas para ajudar.
Aqui é uma lista, seria com o `-` e sem o ponto final

2017-11-29 13:07 UTC, woliveiras commented on meetings/minutes/doc/20171126.md
> +- tirar o Luiz (papa _issue_ do caraio).
Pode até apagar essa linha por que é uma zoeira, mano

2017-11-29 13:07 UTC, woliveiras commented on meetings/minutes/doc/20171126.md
> +    - express OAuth.
Aqui também não tem ponto final por ser uma lista

2017-11-29 13:07 UTC, woliveiras commented on meetings/minutes/doc/20171126.md
> +- não da para entender como as issues se conectam.
Aqui também não tem ponto final por ser uma lista

2017-11-29 13:08 UTC, woliveiras commented on meetings/minutes/doc/20171126.md
> +    - centralizar em uma doc nossa arquitetura (Luiz e Rogerio vão pegar pra fazer); e
Não precisa do `e` no final, pois é uma lista

2017-11-29 13:08 UTC, woliveiras commented on meetings/minutes/doc/20171126.md
> +    - como centralizar as informações?? - ficou definido a criação de uma Wiki (criar o repositório plataforma / William).
Aqui também não tem ponto final por ser uma lista

2017-11-29 13:08 UTC, woliveiras commented on meetings/minutes/doc/20171126.md
> +    - Git Huski / front também (Luiz e David @GesrobDavid).
Aqui também não tem ponto final por ser uma lista

2017-11-29 13:08 UTC, woliveiras commented on meetings/minutes/doc/20171126.md
> +    - Colocar lint hades (Luiz) - TENTAR fazer melhor; e
Aqui também não precisa do `e`

2017-11-29 13:08 UTC, woliveiras commented on meetings/minutes/doc/20171126.md
> +    - issues pedindo os vídeos por sessão.
Aqui também não tem ponto final por ser uma lista

2017-11-29 13:08 UTC, woliveiras commented on meetings/minutes/doc/20171126.md
> +    - documentar melhor TUDO; e
Aqui também não precisa do `e` e do ponto final no último item

2017-11-29 13:09 UTC, woliveiras requested changes
Nos locais onde eram listas você removeu os `-` é necessário voltar com isso pra que aconteça a formatação visual do GitHub

2017-11-29 15:23 UTC, david81brs commented on meetings/minutes/doc/20171126.md
> +## Reunião do dia 26/11/2017.
Veja agora.

2017-11-29 15:28 UTC, david81brs commented
Desculpe, mas não removi indicadores de lista "-", só inseri ";" nas listagens. Um segundo _commit_ foi realizado removendo essas sugestões.
:+1:

2017-12-02 11:34 UTC, woliveiras approved these changes

2017-12-02 11:34 UTC, woliveiras commented
Valeu, @david81brs!! :metal:

2017-12-02 11:34 UTC, merged